### PR TITLE
Remove Google; replace with PrivacyTools

### PR DESCRIPTION
**Pull request by resynth1943**
This commit replaces Google's proprietary, closed-source and intrusive search engine with that of PrivacyTools.

PrivacyTools is known for their dedication to ensuring people can have privacy online.
Meanwhile, Google tries to annihilate any vision of privacy, by stalking ordinary users every day of their lives.

Therefore, I do not think it's wise to support Google.

### CODE REVIEW

**Comment by ddemaio** [comment]
Thank you @resynth1943. This will make quite a few people happy.

**Comment by TheEvilSkeleton** [comment]
You are right, thank you so much for merging it

**Comment by taminaru** [comment]
Your care for people's privacy is something to respect, I kindly offer you a big thank you.

**Comment by hellcp** [comment]
We haven't been using this site for a few weeks already, why are there PRs submitted and accepted here?

**Comment by resynth1943** [comment]
I use it :-)

**Comment by hellcp** [comment]
We don't have a current version of this deployed anywhere, do you run it on a server or something?

**Comment by resynth1943** [comment]
@hellcp Basically, yeah.

@ddemaio Could you rebase the gh-pages branch onto master, please?

**Comment by kevinlekiller** [comment]
@resynth1943 The link in the Readme still uses google, does that link need to be updated?

**Comment by kevinlekiller** [comment]
I guess the issue is https://github.com/openSUSE/searchPage/tree/gh-pages not up to date with master? It hasn't been updated in 5 years.

**Pull request merged**
